### ISSUE TITLE
Can't push branches

### ISSUE THREAD

**Issue by enekodr** [Rikhardt90/react-astrocodex#1]
I was trying to contribute to the project by creating a pull request from a branch, called it `fix-pagination`. However, I receive this error while pushing the new branch:
```
ERROR: Permission to Rikhardt90/react-astrocodex.git denied to enekodr.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

Can you please check the repository settings to confirm contributors have write access?

**Comment by Rikhardt90** [comment]
Hi, I´ve sent you an invitation to collaborate in the project. Please try again and let me know if there are any more issues
Regards
